---
settings:
  name: SnapManager for Hyper-V
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: 適用於Hyper-V文件SnapManager
    url: "/index.html"
  - title: 版本資訊
    url: "/release-notes.html"
  - title: Hyper-V的功能SnapManager
    url: "/concept-what-snapmanager-for-hyper-v-is.html"
    entries:
    - title: 如何運用SnapManager 適用於Hyper-V的功能
      url: "/concept-what-you-can-do-with-snapmanager-for-hyper-v.html"
    - title: Hyper-V限制的列舉SnapManager
      url: "/concept-snapmanager-for-hyper-v-limitations.html"
    - title: 資料管理概念
      url: "/concept-data-management-concepts.html"
  - title: 安裝SnapManager Hyper-V的需求清單
    url: "/reference-list-of-requirements-for-installing-snapmanager-for-hyper-v.html"
    entries:
    - title: 適用於Hyper-V的for Hyper-V授權SnapManager ONTAP
      url: "/reference-snapmanager-for-hyper-v-licensing-for-ontap.html"
    - title: Hyper-V父主機需求
      url: "/reference-hyper-v-parent-host-requirements.html"
    - title: Windows Server環境的修補程式需求
      url: "/reference-hotfix-requirements-for-windows-server-environments.html"
    - title: 授權需求
      url: "/reference-license-requirements.html"
    - title: 使用遠端主機安裝精靈的需求
      url: "/reference-requirements-for-remote-host-install.html"
  - title: 安裝SnapManager 適用於Hyper-V的
    url: "/concept-install-snapmanager-for-hyper-v.html"
    entries:
    - title: 下載SnapManager 適用於Hyper-V的功能
      url: "/task-download-snapmanager-for-hyper-v.html"
    - title: 適用於Windows的安裝順序SnapDrive 和SnapManager 適用於Hyper-V的更新順序
      url: "/concept-installation-order-for-snapdrive-for-windows-and-snapmanager-for-hyper-v.html"
    - title: 安裝SnapManager 適用於Hyper-V的
      url: "/task-install-snapmanager-for-hyper-v.html"
    - title: 在SnapManager 節點或主機上遠端安裝或解除安裝適用於Hyper-V的功能
      url: "/task-remotely-install-or-uninstall-snapmanager-for-hyper-v-on-nodes.html"
    - title: 用於無聲安裝的命令列參數清單與說明
      url: "/reference-command-line-switch-descriptions.html"
  - title: 在SnapManager Windows上解除安裝適用於Hyper-V的功能
    url: "/concept-uninstall-snapmanager-for-hyper-v-on-windows.html"
    entries:
    - title: 解除安裝SnapManager 適用於Hyper-V的功能
      url: "/task-uninstall-snapmanager-for-hyper-v.html"
  - title: 設定SnapManager 適用於Hyper-V的功能
    url: "/concept-configure-snapmanager-for-hyper-v.html"
    entries:
    - title: 儀表板設定
      url: "/concept-dashboard-settings.html"
    - title: 設定主機
      url: "/concept-configure-hosts.html"
      entries:
      - title: 新增Hyper-V父主機或主機叢集的需求
        url: "/reference-requirements-for-adding-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 新增Hyper-V父主機或主機叢集
        url: "/task-add-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 管理儲存連線設定
        url: "/task-manage-storage-connection-settings.html"
      - title: 檢視Hyper-V父主機或主機叢集
        url: "/task-view-a-hyper-v-parent-host-or-host-cluster.html"
      - title: 檢視虛擬機器
        url: "/task-view-a-virtual-machine.html"
      - title: 適用於SnapManager Hyper-V作業的Hyper-V虛擬機器的Migrat
        url: "/task-migrate-a-hyper-v-virtual-machine-to-support-snapmanager-for-hyper-v-operations.html"
      - title: 匯入或匯出主機與資料集組態資訊
        url: "/task-import-or-export-host-and-dataset-configuration-information.html"
      - title: 移除Hyper-V父主機或父主機叢集
        url: "/task-remove-a-hyper-v-parent-host.html"
      - title: 事件通知設定
        url: "/concept-event-notification-settings.html"
        entries:
        - title: 設定電子郵件通知
          url: "/concept-configure-multiple-recipients-for-email-notifications-in-smhv.html"
      - title: 報告路徑設定
        url: "/concept-report-path-settings.html"
    - title: 設定SnapInfo目錄設定
      url: "/concept-configure-snapinfo-directory-settings.html"
      entries:
      - title: 設定SnapInfo LUN
        url: "/task-set-up-a-snapinfo-lun.html"
      - title: 變更SnapInfo目錄路徑
        url: "/task-change-the-snapinfo-directory-path.html"
    - title: 設定資料集
      url: "/concept-configure-datasets.html"
      entries:
      - title: 建立資料集的需求
        url: "/reference-requirements-for-creating-a-dataset.html"
      - title: 建立資料集
        url: "/task-create-a-dataset.html"
      - title: 修改資料集
        url: "/task-modify-a-dataset.html"
      - title: 檢視資料集
        url: "/task-view-a-dataset.html"
      - title: 刪除資料集
        url: "/task-delete-a-dataset.html"
    - title: 設定原則
      url: "/concept-configure-policies.html"
      entries:
      - title: 將原則新增至資料集的需求
        url: "/reference-requirements-for-adding-policies-to-a-dataset.html"
      - title: 新增原則
        url: "/task-add-policies.html"
      - title: 修改原則
        url: "/task-modify-policies.html"
      - title: 檢視原則
        url: "/task-view-policies.html"
      - title: 刪除原則
        url: "/task-delete-policies.html"
    - title: 設定SMB上Hyper-V的SVM或CIFS伺服器
      url: "/concept-configure-svms-or-cifs-servers-for-hyper-v-over-smb.html"
  - title: 管理報告
    url: "/concept-report-management.html"
    entries:
    - title: 檢視資料集報告
      url: "/task-view-a-report.html"
    - title: 檢視主機報告
      url: "/task-view-a-host-report.html"
    - title: 刪除報告
      url: "/task-delete-a-report.html"
  - title: VSS元件
    url: "/concept-overview-of-vss-components.html"
    entries:
    - title: Windows Server 2012及更新版本中的CSV 2.0
      url: "/concept-cluster-shared-volume-2-0-architecture.html"
    - title: 在Windows Server 2012中支援Hyper-V VM的SMB 3.0
      url: "/reference-smb-3-0-support-hyper-v-vms-in-windows-server-2012.html"
    - title: 適用於Hyper-V的解決方法如何使用VSS SnapManager
      url: "/concept-how-snapmanager-for-hyper-v-uses-vss.html"
    - title: VSS硬體供應商需求ONTAP
      url: "/concept-ontap-vss-hardware-provider-requirement.html"
    - title: 檢視已安裝的VSS供應商
      url: "/task-view-installed-vss-providers.html"
    - title: 驗證VSS硬體供應商是否已成功使用
      url: "/task-verify-that-the-vss-hardware-provider-was-used-successfully.html"
  - title: 在SnapManager 支援Hyper-V的支援環境中建立及管理備份工作
    url: "/concept-create-and-manage-backup-jobs-in-snapmanager-for-hyper-v.html"
    entries:
    - title: 手動備份資料集的需求
      url: "/reference-requirements-for-manually-backing-up-a-dataset.html"
    - title: 如何使用適用於Hyper-V的功能來處理儲存狀態備份SnapManager
      url: "/concept-how-snapmanager-for-hyper-v-handles-saved-state-backups.html"
    - title: 手動備份資料集
      url: "/task-manually-backing-up-a-dataset.html"
    - title: 監控備份工作
      url: "/task-monitor-backup-jobs.html"
    - title: 刪除備份
      url: "/task-delete-a-backup.html"
  - title: 從備份複本還原虛擬機器
    url: "/concept-restore-a-virtual-machine.html"
    entries:
    - title: 還原虛擬機器的需求
      url: "/reference-requirements-for-restoring-a-virtual-machine.html"
    - title: 從備份複本還原虛擬機器
      url: "/task-restore-a-virtual-machine-from-a-backup-copy.html"
  - title: 執行叢集作業系統循環升級
    url: "/concept-perform-a-cluster-os-rolling-upgrade.html"
    entries:
    - title: 在混合式作業系統模式中對應LUN
      url: "/task-map-luns-after-the-windows-server-2016-node-addition.html"
    - title: 在所有節點上更新資料集和SnapInfo
      url: "/task-update-the-dataset-and-snapinfo-across-all-nodes.html"
  - title: 執行災難恢復
    url: "/concept-perform-disaster-recovery.html"
    entries:
    - title: 設定SnapManager 適用於Hyper-V的功能以進行容錯移轉
      url: "/concept-configure-snapmanager-for-hyper-v-for-failover.html"
    - title: 從災難恢復容錯移轉中恢復及恢復
      url: "/task-recover-and-restore-from-a-disaster-recovery-failover.html"
    - title: 在災難恢復故障恢復後重新配置儲存系統
      url: "/task-reconfigure-storage-systems-after-a-disaster-recovery-failback.html"
    - title: 還原獨立主機的原始組態
      url: "/task-restore-the-original-configuration-for-standalone-hosts.html"
    - title: 還原叢集主機的原始組態
      url: "/task-restore-the-original-configuration-for-clustered-hosts.html"
  - title: Hyper-V SnapManager 的疑難排解
    url: "/concept-snapmanager-for-hyper-v-troubleshoot.html"
    entries:
    - title: 下列虛擬機器的備份失敗、因為無法在線上進行backedup或找不到要備份的虛擬機器
      url: "/reference-backup-failed-for-the-following-vm-s-since-it-cannot-be-backedup-online-or-no-vm-to-be-found-for-backup.html"
    - title: 查詢IVssWriterCallback介面時發生非預期的錯誤。HR = 8007000、存取遭拒。
      url: "/reference-unexpected-error-querying-for-the-ivsswritercallback-interface-hr-0x80070005.html"
    - title: 備份報告會在報告名稱中使用管理主控台時區資訊
      url: "/reference-backup-reports-use-management-console-time-zone-information-in-report-name.html"
    - title: 未在純IPv6環境中傳送的備份與還原通知
      url: "/reference-backup-and-restore-notifications-not-sent-in-ipv6-only-environments.html"
    - title: 容錯移轉叢集事件ID 5121
      url: "/reference-failover-clustering-event-id-5121.html"
    - title: 還原作業進行期間所進行的虛擬機器備份可能無效
      url: "/reference-virtual-machine-backups-made-while-a-restore-operation-is-in-progress-might-be-invalid.html"
    - title: 虛擬機器自行管理
      url: "/reference-virtual-machine-adding-itself-to-a-dataset.html"
    - title: 使用純IPv6主機的連線時間較長
      url: "/reference-connection-time-is-longer-with-ipv6-only-host.html"
    - title: Volume陰影複製服務錯誤：偵測到內部不一致
      url: "/reference-volume-shadow-copy-service-error-an-internal-inconsistency-was-detected.html"
    - title: Web服務用戶端通道無法連線至機器smhv51_81 cluss上的Configuration Management Service執行個體
      url: "/reference-web-service-client-channel-was-unable-to-connect-to-the-configurationmanagementservice-instance-on-machine-smhv51-81clus.html"
    - title: 用於無聲安裝的MSI自訂屬性
      url: "/reference-msi-custom-property-used-in-silent-installation.html"
    - title: 針對Hyper-V的支援未在主機或儲存系統中獲得授權SnapManager
      url: "/reference-snapmanager-for-hyper-v-is-not-licensed-on-the-host-or-in-the-storage-system.html"
    - title: 容錯移轉後刪除備份
      url: "/reference-secondary-machine-unable-to-delete-backups-after-failover.html"
    - title: 備份失敗後、儲存效能會降低
      url: "/reference-storage-performance-degrades-after-failed-backup.html"
    - title: 已刪除SnapInfo Snapshot複本
      url: "/reference-retention-of-snapinfo-snapshot-copies.html"
    - title: 防毒解決方案造成大量記憶體使用量
      url: "/reference-high-memory-consumption-caused-by-antivirus-solution.html"
    - title: 為每個備份製作兩個Snapshot複本時所耗用的空間
      url: "/reference-space-consumption-when-making-two-snapshot-copies-for-each-backup.html"
    - title: 進行備份時、SSDDiscoveryFileSystemListInfo回應為null SnapDrive
      url: "/reference-error-snapdrive-sddiscoveryfilesystemlistinfo-response-is-null.html"
    - title: 錯誤：VSS要求者-備份元件失敗
      url: "/reference-error-vss-requestor-backup-components-failed.html"
    - title: VSS申請人-備份元件失敗。預期的磁碟未送達系統
      url: "/reference-error-vss-requestor-backup-components-failed-an-expected-disk-did-not-arrive-in-the-system.html"
    - title: VSS申請人-備份元件失敗、並出現部分寫入錯誤
      url: "/reference-dataset-backup-might-fail-with-a-partial-writer-error.html"
    - title: VSS會在NAS備份期間針對Microsoft iSCSI Target VSS Hardware Provider傳回錯誤
      url: "/reference-vss-returns-errors-against-microsoft-iscsi-target-vss-hardware-provider-during-nas-backup.html"
    - title: VSS申請人-備份元件失敗。無法呼叫保留快照集。
      url: "/reference-vss-requestor-backup-components-failed-failed-to-call-keep-snapshot-set.html"
    - title: 支援Hyper-V的MBRLUN SnapManager 不受支援
      url: "/reference-mbr-luns-unsupported-in-snapmanager-for-hyper-v.html"
    - title: 從Hyper-V Manager移除虛擬機器後、備份失敗
      url: "/reference-backup-fails-after-removing-virtual-machine-from-hyper-v-manager.html"
    - title: 某些類型的備份失敗不會導致部分備份失敗
      url: "/reference-some-types-of-failures-do-not-generate-error-message.html"
    - title: 儲存系統磁碟區重新命名後還原失敗
      url: "/reference-restore-failure-after-storage-system-volume-renaming.html"
    - title: 容錯回復後從備份還原
      url: "/reference-restore-from-a-backup-after-failback.html"
    - title: 將資料集更新至新節點時、Web服務用戶端通道無法連線
      url: "/reference-web-service-client-channel-unable-to-connect-while-updating-the-dataset-to-the-new-node.html"
    - title: 資料集不會自動複寫至Windows容錯移轉叢集中的新節點
      url: "/reference-datasets-are-not-automatically-replicated-to-new-nodes-in-a-windows-failover-cluster.html"
    - title: 錯誤1935。安裝組合件零組件時發生錯誤
      url: "/reference-error-1935-an-error-occurred-during-the-installation-of-assembly-component.html"
    - title: 從同一個儲存系統進行的備份工作可能會失敗、而這些工作涉及15個以上的CSV
      url: "/reference-backup-jobs-that-involve-more-than-15-csvs-from-the-same-filer-fail-with-rename-snapshot-error.html"
    - title: 指定的虛擬機器不存在、或無法線上備份
      url: "/reference-either-the-specified-vm-s-are-not-present-or-they-cannot-be-backed-up-online.html"
    - title: 某些平台無法安裝必要的修補程式KB2263829
      url: "/reference-required-hotfix-kb2263829-cannot-be-installed-on-some-platforms.html"
    - title: 備份失敗、出現「陰影複製建立已在進行中」錯誤
      url: "/reference-backup-fail-with-the-error-shadow-copy-creation-is-already-in-progress.html"
  - title: 法律聲明
    url: "/legal-notices.html"
