---
permalink: reference-command-line-switch-descriptions.html 
sidebar: sidebar 
keywords: command, line, switch, perform, silent, installation, enable, script, snapmanager, hyper-v 
summary: 您可以使用命令列切換參數執行無聲安裝、以便使用安裝指令碼來安裝SnapManager 適用於Hyper-V的功能 
---
= 用於無聲安裝的命令列參數清單與說明
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
您可以使用命令列切換參數執行無聲安裝、以便使用安裝指令碼來安裝SnapManager 適用於Hyper-V的功能

下表提供值清單、並說明每個可用的命令列安裝參數。

|===
| 交換器 | 價值 | 說明 


 a| 
無聲模式=
 a| 
1.
 a| 
啟用SnapManager Hyper-V的支援功能、以正確執行無人管理的安裝功能。首次安裝、升級及完整解除安裝時、必須使用此交換器。



 a| 
REINSTALLMODE=
 a| 
 a| 
指定要使用的重新安裝模式。



 a| 
REINSTALLMODE=
 a| 
V
 a| 
表示安裝是從來源套件執行、而且本機套件已快取。請勿在初次安裝SnapManager 適用於Hyper-V的版本時使用此選項重新安裝所有檔案、無論版本、日期或Checksum值為何。



 a| 
REINSTALLMODE=
 a| 
答
 a| 
如果有較舊版本或檔案遺失、請重新安裝SnapManager 適用於Hyper-V檔案的功能。



 a| 
REINSTALLMODE=
 a| 
O
 a| 
表示SnapManager 應重新寫入Hkey_local_machine和HKEY_CLASSES根目錄中所有的Hyper-V必要登錄項目。



 a| 
REINSTALLMODE=
 a| 
m
 a| 
表示SnapManager 應重新寫入來自於Hkey_current_user和Hkey_user-的 所有針對Hyper-V的必要登錄項目。



 a| 
REINSTALLMODE=
 a| 
U
 a| 
重新安裝所有捷徑並重新整理所有圖示、覆寫任何現有的捷徑和圖示。



 a| 
REINSTALL=
 a| 
全部
 a| 
重新安裝SnapManager 所有適用於Hyper-V功能的功能。



 a| 
/LI
 a| 
檔案名稱
 a| 
指定SnapDrive 應產生一個安裝記錄檔。



 a| 
SMHP_LUSES=
 a| 
授權
 a| 
指定適當且有效SnapManager 的適用於Hyper-V授權的功能。



 a| 
InstallLDIR=
 a| 
目標安裝目錄
 a| 
指定SnapManager 安裝for Hyper-V的目標安裝目錄。只有SnapManager 在初次安裝適用於Hyper-V的功能時、才需要此交換器。



 a| 
SVCUSERNAME =
 a| 
網域\使用者名稱
 a| 
指定SnapManager 在無人管理安裝期間、適用於Hyper-V的網域和使用者名稱。



 a| 
SMHVSRV_密碼=
 a| 
密碼
 a| 
指定SMHVSRV_password使用者的密碼。



 a| 
SMHVSRV_COFFIRMUSERPASSEND=
 a| 
密碼
 a| 
確認SMHVSRV_COFFIRMUSERPASS協會 使用者的密碼。



 a| 
SMHV_WebSRV_tcp_port
 a| 
連接埠號碼
 a| 
指定SnapManager 供Hyper-V Web服務使用的連接埠用於Net.TCP。預設連接埠為808。

|===
下列語法顯示全新安裝：

「etup.exe /s /v」/qn silent_mode=1 /L* v SMHVInstall.log SVCUSERNAME =網域\使用者名稱SMHVSRV_Password=密碼SMHVSRV_CONFIRMUSERPASSEV=password」

下列語法顯示升級：

「etup.exe /s /v」/qn REINSTALLMODE=vamus REinstall=all silent_mod=1 /L* v SMHVUpgrade.log SVCUSERNAME =網域\使用者名稱SMHVSRV_Password=密碼SMHVSRV_CONFIRMUSERPASSCED=password」

下列語法顯示解除安裝：

「etup.exe /s /x /v」/qn silent_mod=1 /L* v SMHVuninstall.log」
