---
permalink: reference-requirements-for-manually-backing-up-a-dataset.html 
sidebar: sidebar 
keywords: backup, dataset, manual, first, name, describe, type, option, retention, policy, requirement 
summary: 若要手動備份資料集、您必須先命名並說明資料集、選擇備份類型和選項、然後設定保留原則。 
---
= 手動備份資料集的需求
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
若要手動備份資料集、您必須先命名並說明資料集、選擇備份類型和選項、然後設定保留原則。



== 備份名稱與說明

您必須為備份指派名稱和說明。

備份的預設命名慣例為DatasetName_Timestamp.您可以變更備份名稱中的所有項目、但時間戳記除外、時間戳記永遠會顯示在備份名稱的一部分。

備份名稱和說明僅限於下列字元：

* a到z
* 從A到Z
* 0至9
* _（底線）
* -（連字號）




== 原則選擇

您必須決定要用於隨需備份的原則。

您可以在備份精靈中選取特定原則。您可以覆寫保留或複寫原則、以及與原則相關聯的指令碼、而不需變更原則本身。

您也可以選擇「無」、如此一來、您無需建立任何原則、即可進行隨需備份。此選項使用保留原則、複寫原則和指令碼的預設值。



== 保留價值

您可以選擇覆寫所選原則中指定的保留原則。如果您這麼做、則必須決定刪除每小時、每日、每週、每月或無限次備份複本之前、保留的最短時間長度。

您可以根據時間或指定的備份數量來保留備份。例如、您可以保留10個最新的備份、也可以刪除15天之前的備份。



== 備份類型

您可以執行應用程式一致或損毀一致的備份。



== 備份選項

您可以允許儲存狀態備份。

如果一或多個虛擬機器無法在線上備份、則支援Hyper-V的預設行為SnapManager 是使備份失敗。如果虛擬機器處於儲存狀態或關機狀態、您就無法執行線上備份。在某些情況下、虛擬機器會處於儲存狀態或關機以進行維護、但即使無法進行線上備份、仍必須繼續備份。為達成此目的、您可以將處於儲存狀態的虛擬機器或關機移至不同的資料集、其中的資料集具有允許儲存狀態備份的原則。

您也可以選取「允許儲存的狀態VM備份」核取方塊、以修改現有原則。這可讓SnapManager Hyper-V在儲存狀態下備份虛擬機器。如果您選取此選項、SnapManager 則當Hyper-V VSS寫入器將虛擬機器備份至儲存狀態、或執行虛擬機器的離線備份時、適用於Hyper-V的功能不會失敗備份。執行儲存狀態或離線備份可能會導致停機。

「已發佈的應用程式一致備份」功能可讓在合作夥伴叢集節點上執行的多個VM在從備份節點建立的單一硬體Snapshot複本中保持一致。在CSV 2.0 Windows磁碟區上執行的所有VM、都能在Windows容錯移轉叢集中的多個節點上支援此功能。



== SnapMirror備份中的二線儲存設備

這些選項可讓您接受SnapMirror關係中定義的次要儲存設備適用的選項。您可以選擇*備份後更新SnapMirror *。在Vault標籤選項窗格下、您可以選擇*備SnapVault 份後更新支援*。如果您選擇*在SnapVault 備份後更新*、則必須從下拉式功能表中選擇一個資料保險箱標籤、或輸入自訂標籤。



== 備份指令碼

您可以覆寫所選原則中指定的指令碼選項。

除非您在指令碼中指定特定主機、否則這些指令碼會在所有資料集成員主機上執行。

*相關資訊*

http://technet.microsoft.com/library/cc753637(WS.10).aspx["Microsoft TechNet：Hyper-V"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-buvault/home.html["《使用《不適用》指南的《》（英文）9 Volume Backup》ONTAP SnapVault"]
